Add milvus
crweiner/hacktoberfest-swag-list pull request #405
Opened 2021-10-01 06:43 UTC by Mridulbirla13

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2021-10-01 14:48 UTC, crweiner commented
Hey @Mridulbirla13! 👋 Thanks for your PR to the Hacktoberfest Swag List! Would you be able to tackle the [md flags from Code Climate](https://codeclimate.com/github/crweiner/hacktoberfest-swag-list/pull/405)? I setup that robotic overlord to make sure that the markdown -> HTML gets rendered properly and consistently for the site. 🤖 

Thank you!

2021-10-01 17:29 UTC, Mridulbirla13 commented
Hey @crweiner , I have solved issues stated by Code Climate Bot.  Can you further guide me, how to further resolve conflict?

2021-10-02 02:47 UTC, crweiner requested changes
Hey @Mridulbirla13! There's a few things I'd like you to update, please. Please let me know when you're ready for me to take another look! 👀 Thanks! 👍

2021-10-02 02:47 UTC, crweiner commented on README.md
> +
Following the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing), I'd love to see you format this entry again. Use the examples from line 280-287 above.

2021-10-02 02:47 UTC, crweiner commented on README.md
> +- **Notes**: Check out [Milvus Community Forum](https://discuss.milvus.io/c/hacktoberfest/9) and view the [Hacktoberfest thread here.](https://discuss.milvus.io/t/join-hacktoberfest-2021-with-us/72)
I formatted this to be more in line with the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing). Using this as a template, please edit the other entries below.

2021-10-02 02:47 UTC, crweiner commented on README.md
> +
Following the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing), I'd love to see you format this entry again. Use the examples from line 280-287 above.

2021-10-02 04:01 UTC, crweiner commented
I appreciate your work on this! Milvus was just added in PR #408. I highly encourage you to look for more companies offering unique Hacktoberfest swag, because there's lots more out there! 🔍 

Thank you again and I hope you have a marvelous Hacktoberfest!!

2021-10-02 04:01 UTC, closed without merging