Added MindsDB to the Swag list
crweiner/hacktoberfest-swag-list pull request #582
Opened 2022-10-02 04:12 UTC by amitmishra11

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [X] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [X] I'm not adding a company from the blocklist
3. [X] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2022-10-02 04:14 UTC, amitmishra11 commented
@crweiner  I tried removing the conflicts but am not able to remove flags that codeclimate  puts in.
please see

2022-10-02 04:41 UTC, crweiner requested changes
Hey @amitmishra11! 👋 Thanks for the new PR! Just a few things to adjust, please. We've got to keep the bots happy before they decide to revolt. 🤖 

Please let me know if you need help with the merge conflict or markdown formatting! I'd like to give you a chance to learn and try on your own!

Be sure to check the [Netlify deploy preview ](https://deploy-preview-582--hacktoberfest-swag-list.netlify.app/list)to make sure that things look the way you'd like. Please ping me again if you need any help. 👍

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +>>>>>>> e2b3adf2093b5a410fba097c66210c512628e5e4
It looks like you have a merge conflict here. Please remove the duplicate text and keep the ones that have `{:target="\_blank"}` after the links.

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +
The Markdown linter in CodeClimate is looking for 1 paragraph space, not 2, between each header.

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +
The Markdown linter in CodeClimate is looking for 1 paragraph space, not 2, between each header.

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +    - For every 10 points, you will receive one entry into the draw for the awesome Razer Blade 15 Laptop powered by the top NVIDIA GeForce RTX 3080 Ti GPU, 14-core Intel i9 CPU and more…
It's a small thing, but please make sure there aren't any stray spaces, tabs, paragraph breaks, line breaks, etc. Keeping these stray whitespace marks in can affect the Markdown -> HTML conversion during CI/CD building.

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +    3rd place: $200
Make sure that you follow Markdown formatting for unordered lists for here and lines 171 - 173 as well.

2022-10-02 04:41 UTC, crweiner commented on docs/list.md
> +    3rd place: $200
[This site may help](https://www.markdownguide.org/basic-syntax/#unordered-lists)

2022-10-02 08:40 UTC, amitmishra11 commented on docs/list.md
> +    - For every 10 points, you will receive one entry into the draw for the awesome Razer Blade 15 Laptop powered by the top NVIDIA GeForce RTX 3080 Ti GPU, 14-core Intel i9 CPU and more. You can als
@crweiner  Thank you so much for the help! Telling me about each issue separately. With that help, I was able to knock 9 out of 10 issues in the previous commit. Just this one is left

2022-10-03 02:16 UTC, crweiner commented on docs/list.md
> +    - For every 10 points, you will receive one entry into the draw for the awesome Razer Blade 15 Laptop powered by the top NVIDIA GeForce RTX 3080 Ti GPU, 14-core Intel i9 CPU and more. You can als
You did a really, really good job! Thank you very much for tackling the issues that CodeClimate flagged! I appreciate it and I hope it taught you something along the way, @amitmishra11!

2022-10-03 02:19 UTC, crweiner approved these changes

2022-10-03 02:24 UTC, crweiner commented
Hello again @amitmishra11! 👋 Thank you so much for adding MindsDB to the 2022 Hacktoberfest Swag List! 🎉  I loved seeing how you took my review into consideration and made some adjustments to your PR. I hope that this was a good learning experience for you! This should give you a boost in confidence and a great start to Hacktoberfest! 

Let's send some great people to MindsDB so they can receive some helpful PRs! 🚀 

![you rock](https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif)

Thanks again, and happy Hacktoberfest! 🎃

2022-10-03 02:24 UTC, merged