feat: added NativeScript to Hacktoberfest swag list
crweiner/hacktoberfest-swag-list pull request #651
Opened 2022-10-07 04:23 UTC by akk312000

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ ] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2022-10-07 04:29 UTC, akk312000 commented
Solves Issue #649 @crweiner .

2022-10-07 05:09 UTC, crweiner requested changes
Hey @akk312000! 👋 Thanks for your PR! I've fixed the trailing whitespace flags from Code Climate for you (sometimes an IDE or your computer adds them as you type) and would like some small tweaks as pointed out below, please. Thank you! 😄

2022-10-07 05:09 UTC, crweiner commented on docs/list.md
> +    - Tweet about it and mention @NativeScript.
Can you please have the @Nativescript part link to their Twitter account?

2022-10-07 05:09 UTC, crweiner commented on docs/list.md
> +    - DM us your address to get free swag.
Please don't DM _me_ your address! 😆 Please make this clear that NativeScript is looking for a DM.

2022-10-07 05:37 UTC, akk312000 commented
@crweiner  Updated the PR, please have a look, Thanks.

2022-10-08 03:11 UTC, crweiner approved these changes
Thank you for the updates, @akk312000! I appreciate it! Everything looks great now, so let's get this on the Swag List! 

Thank you for your PR and have a great Hacktoberfest!

![thank you](https://media.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif)

2022-10-08 03:11 UTC, merged

2022-10-08 03:12 UTC, akk312000 commented
@crweiner A big Thanks to you for allowing me to contribute to it :). 😁