Update Readme.md
crweiner/hacktoberfest-swag-list pull request #665
Opened 2022-10-08 15:53 UTC by AbhiiVops

Corrected some of the mistakes in Readme.md

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ ] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2022-10-09 04:06 UTC, crweiner requested changes
Hi @AbhiiVops! Thank you for your PR to the Hacktoberfest Swag List! A few things to address below, please. 

Ping me when you're ready for me to take another look! 👀

2022-10-09 04:06 UTC, crweiner commented on docs/list.md
> +
Thank you for adding Devtron to the Swag List! I'd encoruage you to look at the [Contributing guidelines](https://hacktoberfestswaglist.com/contributing/) to make sure you're formatting things correctly (as well as other entries on the List). 

Netlify will also provide you with a build preview with each new commit, so feel free to use those previews to make sure that things look the way you want them to.

2022-10-09 04:06 UTC, crweiner commented on Readme.md
> -Hello all you beautiful nerds and welcome to another year of [Hacktoberfest](https://hacktoberfest.com/)! at the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com)
I think that all of these proposed changes to the Readme file are of low value. I'd much rather appreciate you adding an organization to the Swag List from one of the Issues. Please un-do these propsed chages to the Readme you made; I will not be able to merge any _good contribution_ with this still in place.

2022-10-09 19:02 UTC, AbhiiVops commented
> 

I have made the suggested changes. Please check once

2022-10-10 14:15 UTC, AbhiiVops commented
> Hi @AbhiiVops! Thank you for your PR to the Hacktoberfest Swag List! A few things to address below, please.
> 
> Ping me when you're ready for me to take another look! 👀

I have made the changes. Please have a look at it

2022-10-11 03:25 UTC, crweiner requested changes
Hello @AbhiiVops, there are lots of required changes that need to take place before I can merge your contribution.

The biggest things are:

1. Please do not just copy and paste text from the site, as the wording is often all off.
2. Please check your spelling, punctuation, capitalization, etc.
3. Please re-read what the `-**Issues**:` line item is for.
4. Please include all contribution/swag opportunities offered by an organization, not just one.

Ping me again when you'd like another look, thank you!

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +#### **devtron**
I started to make the changes myself to this entry, but there were so many that I stopped. I would like you to please review your PR and format this Devtron entry differently. 

Devtron appears to be rewarding people for meaningful PRs during their several different events. This PR appears to only capture their Art-A-Thon event, not anything else.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **Requirements**:
Please list the requirements of each event, summarized (do not just copy and paste from their Readme file...).

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **How to sign up**: Open this [Github Repo](https://github.com/devtron-labs/devtron) ,Fork it and star it . When submitting a PR please add Hacktoberfest in the PR Description. This would give us a
Please double check all formatting, spelling, punctuation, etc.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **Issues**: Checkout [Devtron Repo](https://github.com/devtron-labs/hacktoberfest2022/blob/main/README.md#book-contribution-guidelines).
The Issues section, if included (as it's optional), is when an organization wants to highlight certain GitHub Issues as counting for Hacktoberfest. If that is not the case, then it should not be included here.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +#### **devtron**
```suggestion
#### **Devtron**
```

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +#### **hacksquad**
```suggestion
#### **HackSquad**
```

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **Swag**: T-shirts, hacksquad printed cups,carry bags,stickers,Hoodie
Please check your punctuation, spacing, spelling, etc.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **Requirements**:  Register to the HackSquad using your GitHub, Join a squad or get assigned to a random squad, contribute code and get Swag!
Don't just copy and place, please. And again, check punctuation and spelling, please.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **How to sign up**: Open this [Hacksquad](https://www.hacksquad.dev/) ,Click on join now and there you go.
```suggestion
- **How to sign up**: [Sign up on the Hacksquad website](https://www.hacksquad.dev/).
```

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +- **Issues**: Checkout [goodfirstissue](https://goodfirstissue.dev/) and contribute to it.
See above note on the Issues section regarding Devtron; please remove Issues here as it's not relevant.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +    - The top 60 squads will win awesome swag! around ~300 winners!
How many people are on a squad?

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +    - Each hour we calculate the number of MERGED PRs of each squad member and sum them all up. Each PR is worth 1 point. By the end of the event, the top 60 squads will win awesome swag!
"Each hour **_we calculate_**..." _We_ over here at the Hacktoberfest Swag List don't do any calculations! Again, please don't copy and paste, you need to re-write what they have to instead be relevant to the visitors of this site/repo.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +
Please make the robot happy here.

2022-10-11 03:25 UTC, crweiner commented on docs/list.md
> +    - Each hour we calculate the number of MERGED PRs of each squad member and sum them all up. Each PR is worth 1 point. By the end of the event, the top 60 squads will win awesome swag!
Please make the robot happy here.

2022-10-12 04:49 UTC, crweiner commented
Devtron has been added in #662, please feel free to open a new PR to add HackSquad and follow the edits I suggested above! 👍

2022-10-12 04:49 UTC, closed without merging