Newb
crweiner/hacktoberfest-swag-list pull request #805
Opened 2023-10-09 14:53 UTC by Shorya18

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up
#801 
Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2023-10-09 17:20 UTC, crweiner commented
Hello @Shorya18! Can you please update this PR title to reflect the company you're looking to add to the Swag List, and verify that all looks as intended in the site preview: https://deploy-preview-805--hacktoberfest-swag-list.netlify.app/list/#odigos

There are some formatting issues I'd love for you to see and change. Be sure you're following the [Contributing guide](https://hacktoberfestswaglist.com/contributing/). Thanks!

2023-10-10 09:34 UTC, Shorya18 commented
> Hello @Shorya18! Can you please update this PR title to reflect the company you're looking to add to the Swag List, and verify that all looks as intended in the site preview: https://deploy-preview-805--hacktoberfest-swag-list.netlify.app/list/#odigos
> 
> There are some formatting issues I'd love for you to see and change. Be sure you're following the [Contributing guide](https://hacktoberfestswaglist.com/contributing/). Thanks!

Hey I have changed the tittle name to the company's name which I want to add in the list.
thanks

2023-10-10 22:46 UTC, crweiner requested changes
Hi @Shorya18, thank you for updating the title of this PR to match the organization you are looking to add! I would like to give you a chance to review the things I've pointed out as well. Please be sure to view the Netlify deployment and make sure that everything for Odigos looks as intended.


Please ping me when you'd like me to take another look, thanks!

2023-10-10 22:46 UTC, crweiner commented on docs/list.md
> +- **Notes**: [Full details are mentioned [here](https://github.com/keyval-dev/odigos/blob/main/README.md).
```suggestion
- **Notes**: Full details are mentioned [here in the repo Readme](https://github.com/keyval-dev/odigos/blob/main/README.md).
```
The

2023-10-10 22:46 UTC, crweiner commented on docs/list.md
> +- **Swag**: Swag (Specific Swags not mentioned)
The swag is mentioned in the[ Readme file](https://github.com/keyval-dev/odigos/blob/main/README.md), can you please update this?

2023-10-10 22:46 UTC, crweiner commented on docs/list.md
> +- **Requirements**: Make 3 successful merged PRs by October 20,2023  to win swags
Please watch your spacing here
```suggestion
- **Requirements**: Make 3 successful merged PRs by October 20, 2023
```

2023-10-20 14:45 UTC, vimode commented
Hey @crweiner I think some of these old PRs which are not being updated by the PR authors should be closed and corresponding issues be made open for others to add them to the list. It would be much simpler for you.

2023-10-26 03:39 UTC, crweiner commented
Closed due to inactivity

2023-10-26 03:39 UTC, closed without merging