Added Revert into hacktoberfest swag list issue - #830
crweiner/hacktoberfest-swag-list pull request #835
Opened 2023-10-15 14:42 UTC by nooras

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Closes: #830 

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2023-10-15 17:15 UTC, vimode requested changes
Thank you for contributing.

If these changes cause any code climate errors, can you please fix those too? Thank you.

2023-10-15 17:15 UTC, vimode commented on docs/list.md
> +- **Swag**: Stickers (100 pumpkins), Mug (250 pumpkins), Cap (250 pumpkins), Tshirt (500 pumpkins), Hoodie (1000 pumpkins)
```suggestion
- **Swag**: Stickers, Mug, Cap, T-shirt, and Hoodie.
```

2023-10-15 17:15 UTC, vimode commented on docs/list.md
> +- **Notes**: More details [available here](hhttps://twitter.com/revertdotdev/status/1712834581383233988).
```suggestion
- **Notes**: More details [available here](https://twitter.com/revertdotdev/status/1712834581383233988).
```

2023-10-15 17:15 UTC, vimode commented on docs/list.md
> +- **Issues**: All the [open issues](https://github.com/revertinc/revert/issues)
```suggestion
- **Issues**: All the open [hacktoberfest issues](https://github.com/revertinc/revert/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).
```

2023-10-15 18:15 UTC, nooras commented
> Thank you for contributing.
> 
> If these changes cause any code climate errors, can you please fix those too? Thank you.

Hi @vimode ,
Can you please explain a little more? I didn't get it !
Shall I just click on resolve conversation and commit the changes?
Shall I add pumpkins points in requirement?

2023-10-15 18:27 UTC, vimode commented
Hey @nooras, the dark blue highlighted parts are the changes I did.
I removed the pumpkins points from the Swag field, its fine to keep them in requirements. And I also fixed the twitter link.

Yes you can click *commit the changes* to make those changes in this PR. 
Once you do that, this PR will get updated with those changes and all the checks will run again, codeclimate will do its thing to notify of any new errors.

2023-10-16 16:03 UTC, nooras commented
Hi @vimode 
Have committed changes as you requested & also added 1 more point in requirements for that pumpkins points.
(I have made lots of commit 😅)
Kindly check and let me know if more changes are required.

Thanks for your suggestions

2023-10-26 04:01 UTC, crweiner commented
Howdy @nooras, thank you for your PR to add Revert to the Hacktoberfest Swag List! And thank you too @vimode for the incredible assistance and for reviewing this PR! I've made some further tweaks, but it looks like things are now good to go, thanks again!

![thumbs up](https://media.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif)

2023-10-26 04:01 UTC, merged