Added Zilliz to the list
crweiner/hacktoberfest-swag-list pull request #836
Opened 2023-10-15 18:32 UTC by bharatr21

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Closes #831 

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2023-10-16 03:58 UTC, vimode requested changes
Hey @bharatr21 
The Zilliz Hacktoberfest page also mentions a few other ways to contribute, please add those in the requirements, as a way to encourage low/no-code contributions too.

2023-10-16 03:58 UTC, vimode commented on docs/list.md
> +- **Notes**: Check out [Zilliz Hacktoberfest page](https://zilliz.com/hacktoberfest) and the [Contribution Guide](https://github.com/milvus-io/milvus/blob/5ba158a3f559e424e8bd98f3c2032d53f8cf310c/CON
```suggestion
- **Notes**: Check out [Zilliz Hacktoberfest page](https://zilliz.com/hacktoberfest) and the [Contributing Guide](https://github.com/milvus-io/milvus/blob/5ba158a3f559e424e8bd98f3c2032d53f8cf310c/CONTRIBUTING.md) for more details.
```

2023-10-16 09:29 UTC, bharatr21 commented on docs/list.md
> +- **Notes**: Check out [Zilliz Hacktoberfest page](https://zilliz.com/hacktoberfest) and the [Contribution Guide](https://github.com/milvus-io/milvus/blob/5ba158a3f559e424e8bd98f3c2032d53f8cf310c/CON
Updated this

2023-10-16 09:29 UTC, bharatr21 commented
@vimode updated other ways to contribute. Please re-review

2023-10-26 04:05 UTC, crweiner commented
Howdy @bharatr21, thank you for your PR to add Zilliz to the Hacktoberfest Swag List! I appreciate it, especially @vimode's assist on making sure we had low/no-code options as well! Happy to get this merged!

![happy cat](https://media.giphy.com/media/6PtBZqT8earZ3XBTTL/giphy.gif)

2023-10-26 04:05 UTC, merged