Add Composio to the Hacktoberfest Swag List
crweiner/hacktoberfest-swag-list pull request #920
Opened 2024-10-02 09:04 UTC by Brijeshthummar02

issue #916 

1. [x] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [x] I'm not adding a company from the blocklist
3. [x] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2024-10-02 14:18 UTC, vimode requested changes
These would help contributors to reach the necessary links in minimal clicks!

2024-10-02 14:18 UTC, vimode commented on docs/contributing.md
> +- **Issues**: Optional link to Hacktoberfest tagged issues in Composio repositories.
```suggestion
- **Issues**: Open issues [tagged as "hacktoberfest"](https://github.com/ComposioHQ/composio/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Ahacktoberfest)
```

2024-10-02 14:18 UTC, vimode commented on docs/contributing.md
> +- **Notes**: Ensure to submit PRs before October 31, 2024, for swag eligibility.
```suggestion
- **Notes**: [Check out their announcement post for more information.](https://github.com/ComposioHQ/composio/blob/master/HACKTOBER_FEST_2024.md)
```

2024-10-02 14:18 UTC, vimode commented on docs/contributing.md
> +- **Swag**: Stickers, T-shirt
```suggestion
- **Swag**: Stickers and T-shirt
```

2024-10-04 03:06 UTC, crweiner commented
Hi @Brijeshthummar02, thank you for your PR, and also thank you @vimode for suggesting some good corrections. However, this PR is against the Contributing.md file, not the actual list (List.md).

There is another existing PR open for Composio, PR #917, that is in the correct file, so I will move forward with that other one. @Brijeshthummar02, I encourage you to try again with a different PR to add someone else to the list and be extra careful!

2024-10-04 03:06 UTC, closed without merging