Add Opencast to Hacktoberfest swag list
crweiner/hacktoberfest-swag-list pull request #944
Opened 2024-10-07 05:55 UTC by nabeelmohamed

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request, please check off as many of the items below as you can:

1. [ ] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Thanks and Happy Hacktoberfest! :tada:
Tagging @crweiner to take a look. :eyes:

2024-10-07 05:57 UTC, nabeelmohamed commented
typo error *Owncast*

2024-10-07 14:45 UTC, vimode commented
Owncast doesn't seem to be providing exclusive swag for _hacktoberfest_. As far as I remember this list includes only the companies and projects which give swag exclusively for contributions during _hacktoberfest_. 

As per the issues at Owncast,
> Active contributors get an Owncast t-shirt! Ask about it if you feel like you've been contributing and haven't yet been given one.

@crweiner IIRC, isn't this the same reason why Kong is not included in the list anymore?

2024-10-07 16:02 UTC, nabeelmohamed commented
@vimode  you can find the swag details here( https://owncast.online/hacktoberfest/#content-no-code-or-low-code-contributions)

2024-10-07 17:08 UTC, vimode commented
@nabeelmohamed Thank you for confirming their hacktoberfest participation with an appropriate link!
This link should be included in it too for contributors to read about it. 
If you check the other orgs added to the list, you will get an idea where and how it should be added. 
And please do check all the links which are included in the PR to make sure they are not dead. The contributing link is.

2024-10-08 06:22 UTC, vimode requested changes
Suggested some changes.

2024-10-08 06:22 UTC, vimode commented on docs/list.md
> +- **Notes**: Read the [Owncast Contributor Guide](https://owncast.online/docs/contributing/) and for more info check [here](https://owncast.online/hacktoberfest/#content-no-code-or-low-code-contribut
```suggestion
- **Swag**: T-shirt.
- **Requirements**:
	- Make quality code or non-code or low code contributions to Owncast (e.g. fix a bug, write useful documentation, create content around Owncast).
	- After contributing, [fill this form to request a T-shirt.](https://gabekangas.typeform.com/to/Wfx9UHVZ)
- **How to sign up**: No separate signup known.
- **Issues**: All eligible [open issues.](https://github.com/owncast/owncast/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
- **Notes**: Read the [Owncast Contributing Guidelines](https://owncast.online/hacktoberfest/#what-do-you-receive-by-contributing-to-owncast-during-hacktoberfest) for more information.
```

2024-10-08 06:22 UTC, vimode commented on docs/list.md
> +- **Notes**: Read the [contributing guide](https://github.com/gitroomhq/postiz-app/blob/main/CONTRIBUTING.md) for more information.
```suggestion
- **Swag**: T-shirt.
- **Requirements**:
  - You must create an issue before making a pull request.
  - You can also ask to be assigned to an issue. During Hacktoberfest, each issue can have multiple assignees.
  - We have to approve the issue and add a "hacktoberfest" tag.
  - We encourage everybody to contribute to all types of issues. We will only send swag for issues with features and bug fixes (no typos, sorry).
- **How to sign up**: No separate signup known
- **Issues**: All [open issues](https://github.com/gitroomhq/postiz-app/issues)
- **Notes**: Read the [announcement post](https://github.com/gitroomhq/postiz-app#we-participate-in-hacktoberfest-2024-) for more information.
```

2024-10-18 04:59 UTC, crweiner commented
Hi @nabeelmohamed  and @vimode! Thank you for adding Opencast and Postiz to the Hacktoberfest Swag List! I love seeing new organizations participate! I've made some tweaks and am happy to get this live.

Thanks again!

2024-10-18 04:59 UTC, merged